Complete stack script

diff --git a/microservices/aws/vulndb/stack b/microservices/aws/vulndb/stack
--- a/microservices/aws/vulndb/stack
+++ b/microservices/aws/vulndb/stack
@@ -73,10 +73,12 @@ then
 elif [ "$1" == "delete" ]
 then
     # Remove Bucket
-    aws s3 rb s3://$bucketname --region $region --force
+    aws s3 rb s3://$bucketname --region $region --force > /dev/null
 
     # Remove Stack
-    aws cloudformation delete-stack --stack-name $appname
+    echo -e "${YELLOW}Deleting Stack...${NC}"
+
+    aws cloudformation delete-stack --stack-name $appname && echo -e "${GREEN}Stack Deleted Successfully ${NC}" || echo -e "${RED} Stack Delete Error: ${NC}"
 elif [ "$1" == "test" ]
 then
   test_stack
